export const events = [
    {
      slug: "anime-expo-2024",
      image: "/images/event1.png",
      title: "Anime Expo 2024",
      location: "Los Angeles Convention Center, CA",
      date: "July 4-7, 2024",
      time: "10:00 AM - 8:00 PM",
    },
    {
      slug: "sakura-matsuri-festival",
      image: "/images/event2.png",
      title: "Sakura Matsuri Festival",
      location: "Brooklyn Botanic Garden, NY",
      date: "April 27-28, 2024",
      time: "10:00 AM - 6:00 PM",
    },
    {
      slug: "otakon-convention",
      image: "/images/event3.png",
      title: "Otakon Convention",
      location: "Walter E. Washington Convention Center, DC",
      date: "July 26-28, 2024",
      time: "9:00 AM - 9:00 PM",
    },
    {
      slug: "crunchyroll-expo",
      image: "/images/event4.png",
      title: "Crunchyroll Expo",
      location: "San Jose Convention Center, CA",
      date: "August 16-18, 2024",
      time: "10:00 AM - 7:00 PM",
    },
    {
      slug: "demon-slayer-movie-premiere",
      image: "/images/event5.png",
      title: "Demon Slayer Movie Premiere",
      location: "Regal Cinemas, Tokyo",
      date: "June 15, 2024",
      time: "7:00 PM - 10:00 PM",
    },
    {
      slug: "studio-ghibli-retrospective",
      image: "/images/event6.png",
      title: "Studio Ghibli Retrospective",
      location: "Museum of Modern Art, NY",
      date: "September 1-30, 2024",
      time: "11:00 AM - 6:00 PM",
    },
    {
      slug: "cosplay-championship",
      image: "/images/event1.png",
      title: "World Cosplay Championship",
      location: "Chicago Convention Center, IL",
      date: "October 5-6, 2024",
      time: "12:00 PM - 8:00 PM",
    },
    {
      slug: "j-pop-concert-extravaganza",
      image: "/images/event2.png",
      title: "J-Pop Concert Extravaganza",
      location: "Madison Square Garden, NY",
      date: "November 12, 2024",
      time: "7:00 PM - 11:00 PM",
    },
    {
      slug: "manga-artists-workshop",
      image: "/images/event3.png",
      title: "Manga Artists Workshop",
      location: "Art Institute of Seattle, WA",
      date: "August 20-22, 2024",
      time: "9:00 AM - 5:00 PM",
    },
    {
      slug: "attack-on-titan-finale-screening",
      image: "/images/event4.png",
      title: "Attack on Titan Finale Screening",
      location: "AMC Theaters Nationwide",
      date: "December 3, 2024",
      time: "8:00 PM - 11:00 PM",
    },
    {
      slug: "anime-voice-actor-meetup",
      image: "/images/event5.png",
      title: "Anime Voice Actor Meet & Greet",
      location: "Austin Convention Center, TX",
      date: "May 10, 2024",
      time: "2:00 PM - 6:00 PM",
    },
    {
      slug: "pokemon-tournament",
      image: "/images/event6.png",
      title: "Pokemon TCG World Championship",
      location: "Honolulu Convention Center, HI",
      date: "August 15-18, 2024",
      time: "9:00 AM - 7:00 PM",
    },
    {
      slug: "naruto-themed-ramen-fest",
      image: "/images/event1.png",
      title: "Naruto-Themed Ramen Festival",
      location: "San Francisco Pier 39, CA",
      date: "June 22-23, 2024",
      time: "11:00 AM - 9:00 PM",
    },
    {
      slug: "anime-art-exhibition",
      image: "/images/event2.png",
      title: "Contemporary Anime Art Exhibition",
      location: "Getty Center, Los Angeles, CA",
      date: "October 15 - November 30, 2024",
      time: "10:00 AM - 5:00 PM",
    },
    {
      slug: "my-hero-academia-fan-convention",
      image: "/images/event3.png",
      title: "My Hero Academia Fan Convention",
      location: "Orlando Convention Center, FL",
      date: "July 19-21, 2024",
      time: "10:00 AM - 8:00 PM",
    },
    {
      slug: "anime-music-festival",
      image: "/images/event4.png",
      title: "Anime Music Festival",
      location: "Red Rocks Amphitheatre, Denver, CO",
      date: "September 14, 2024",
      time: "6:00 PM - 11:00 PM",
    },
    {
      slug: "one-piece-anniversary-celebration",
      image: "/images/event5.png",
      title: "One Piece 25th Anniversary Celebration",
      location: "Tokyo Dome, Japan",
      date: "July 22, 2024",
      time: "1:00 PM - 9:00 PM",
    },
    {
      slug: "anime-gaming-tournament",
      image: "/images/event6.png",
      title: "Anime Gaming Tournament",
      location: "Las Vegas Convention Center, NV",
      date: "November 8-10, 2024",
      time: "10:00 AM - 10:00 PM",
    },
    {
      slug: "kawaii-culture-festival",
      image: "/images/event1.png",
      title: "Kawaii Culture Festival",
      location: "Little Tokyo, Los Angeles, CA",
      date: "May 25-26, 2024",
      time: "12:00 PM - 8:00 PM",
    },
    {
      slug: "virtual-reality-anime-experience",
      image: "/images/event2.png",
      title: "Virtual Reality Anime Experience",
      location: "Tech Museum, San Jose, CA",
      date: "December 15-31, 2024",
      time: "10:00 AM - 7:00 PM",
    },
  ];